package com.station.stationdownloader.contants

const val UNKNOWN_ERROR = -1

enum class ConfigureError {
    CONFIGURE_ERROR,
    INSUFFICIENT_NUMBER_OF_PARAMETERS,
    NOT_SUPPORT_CONFIGURATION,
}

enum class TaskExecuteError {
    ADD_MAGNET_TASK_ERROR,
    DOWNLOAD_TORRENT_TIME_OUT,
    GET_FILE_SIZE_TIMEOUT,
    GET_HTTP_FILE_HEADER_ERROR,
    NORMAL_TASK_EXISTS,
    NOT_SUPPORT_URL,
    REPEATING_TASK_NOTHING_CHANGE,
    START_TASK_FAILED,
    START_TASK_URL_TYPE_ERROR,
    SUB_TORRENT_INFO_IS_NULL,
    TORRENT_INFO_IS_NULL,
    TORRENT_TASK_EXISTS,
}

enum class SqlError{
    UPDATE_TASK_CONFIG_FAILED
}

enum class EngineError {
    ENGINE_INIT_FAILED
}

